<!DOCTYPE html>
<html>
    <body>
        <div style="width:580px;height:580px;background-color: black;padding: 0px;margin: auto;">
			<div id="aaarevenge_inset" >
				<input type="hidden" name="session_hash" id="sessionHash" value="4e1d102754171d78a86c"/>
				<input type="hidden" name="session_key" id="sessionKey" value="cb8b1a5cc44a50a82413"/>
				<input type="hidden" name="game_id"  id="gameID" value="1375"/>
				<script type="text/javascript" src="http://images.neopets.com/js/phaser.min.js"></script>
				
				<script src="js/utils/Utils.js"></script>
				<script src="js/utils/modal.js"></script>
				
				<script src="js/GameStateConstants.js"></script>
				
				<script src="js/states/BootState.js"></script>
				<script src="js/states/LoadingState.js"></script>
				<script src="js/states/MainMenuState.js"></script>
				<script src="js/states/TiledState.js.php"></script>
				
				<script src="js/prefabs/Prefab.js"></script>

				<script src="js/prefabs/Player.js"></script>
				<script src="js/prefabs/Enemy.js"></script>
				<script src="js/prefabs/King.js"></script>
				<script src="js/prefabs/Power.js"></script>
				<script src="js/prefabs/PowerLife.js"></script>
				<script src="js/prefabs/PowerScore.js"></script>
				<script src="js/prefabs/PowerFreeze.js"></script>
				<script src="js/prefabs/PowerDWatchDog.js"></script>
				
				<script src="js/prefabs/TextPrefab.js"></script>
				<script src="js/prefabs/Lives.js"></script>
				<script src="js/prefabs/Score.js"></script>
				
				<script type="text/javascript" src="js/main.js"></script>
			</div>
    </body>
</html>