<!DOCTYPE xliff PUBLIC "-//XLIFF//DTD XLIFF//EN" "http://www.oasis-open.org/committees/xliff/documents/xliff.dtd" >
<xliff version="1.0" xml:lang="en">
	<file datatype="plaintext" original="20002" source-language="EN">
		<header></header>
		<body>
			<trans-unit id="001" resname="continue_btn">
				<source><![CDATA[Continue]]></source>
			</trans-unit>
			<trans-unit id="001" resname="startgame_btn">
				<source><![CDATA[Play Now]]></source>
			</trans-unit>
			<trans-unit id="001" resname="soundOn_btn">
				<source><![CDATA[Sound On]]></source>
			</trans-unit>
			<trans-unit id="001" resname="soundOff_btn">
				<source><![CDATA[Sound Off]]></source>
			</trans-unit>
			<trans-unit id="001" resname="musicOn_btn">
				<source><![CDATA[Music On]]></source>
			</trans-unit>
			<trans-unit id="001" resname="musicOff_btn">
				<source><![CDATA[Music Off]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howToPlay_btn">
				<source><![CDATA[Instructions]]></source>
			</trans-unit>
			<trans-unit id="001" resname="settings_btn">
				<source><![CDATA[Settings]]></source>
			</trans-unit>
			<trans-unit id="001" resname="quit_btn">
				<source><![CDATA[Exit]]></source>
			</trans-unit>
			<trans-unit id="001" resname="back_btn">
				<source><![CDATA[No]]></source>
			</trans-unit>
			<trans-unit id="001" resname="replay_btn">
				<source><![CDATA[Retry]]></source>
			</trans-unit>
			<trans-unit id="001" resname="exit_btn">
				<source><![CDATA[Exit]]></source>
			</trans-unit>
			<trans-unit id="001" resname="restart_btn">
				<source><![CDATA[Restart Level]]></source>
			</trans-unit>
			<trans-unit id="001" resname="go_btn">
				<source><![CDATA[Go!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="nextLevel_btn">
				<source><![CDATA[Next Level]]></source>
			</trans-unit>
			<trans-unit id="001" resname="yes_btn">
				<source><![CDATA[Yes]]></source>
			</trans-unit>
			<trans-unit id="001" resname="no_btn">
				<source><![CDATA[No]]></source>
			</trans-unit>
			<trans-unit id="001" resname="doRestart_btn">
				<source><![CDATA[Yes]]></source>
			</trans-unit>
			<trans-unit id="001" resname="getResults_btn">
				<source><![CDATA[Next]]></source>
			</trans-unit>
			<trans-unit id="001" resname="doQuit_btn">
				<source><![CDATA[Exit]]></source>
			</trans-unit>
			<trans-unit id="001" resname="restartTitle">
				<source><![CDATA[Are you sure?]]></source>
			</trans-unit>
			<trans-unit id="001" resname="restartBlurb">
				<source><![CDATA[Do you really want to restart this level?]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay1_title">
				<source><![CDATA[Instructions]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay1_blurb1">
				<source><![CDATA[<p>The Petpetpets are attacking! You must stop them from reaching the King’s Flag! To do this you must place Defenders at the windows and on the wall. Locations where you can place a Defender are shown with this Empty Slot icon:</p>
<img src="empty" width="30" height="30" hspace="120" vspace="0" /><br /><br /><p>To place a Defender, click on the Empty Slot icon, and choose the Defender you want from the menu.</p>
<p>Every Petpetpet you defeat earns you a small amount of money, which you can use to buy or upgrade your Defenders.</p>]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay1_blurb2">
				<source><![CDATA[<p>Once placed, Defenders will automatically attack the Petpetpets. Each type of Defender has their own way of fighting.  Different Defenders work better in some places than others, so make sure you think about where you're putting them!</p>
<p>Upgrading Defenders will make them more powerful, but it costs money. You can also sell a placed Defender, but you will only get some of the money back. To upgrade or sell a Defender, click on him and choose the option from the menu.</p>]]></source>
<p>When the King's Flag reaches the bottom of its pole, the game is over. Good luck!</p>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay2_title">
				<source><![CDATA[Instructions - Defenders]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay2_close_range">
				<source><![CDATA[Melee: Powerful short-range attack.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay2_long_range">
				<source><![CDATA[Ranged: Long-range attack, with medium power.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay2_magic">
				<source><![CDATA[Magic: Hits multiple Petpetpets with each attack. Medium-range, medium power.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay2_barrel">
				<source><![CDATA[Barrel Dropper: Drops barrels, and does high damage. May also knock Petpetpets off the wall, so they must start climbing again.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay2_slowing">
				<source><![CDATA[Slowing: Slows down Petpetpets temporarily. Medium range, but only hurts the millipede.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay3_title">
				<source><![CDATA[Instructions - Petpetpets]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay3_spider">
				<source><![CDATA[Aboogala: Fast but weak. They are vulnerable to melee attacks and slowing, but they can web your defenders if they get close!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay3_bug">
				<source><![CDATA[Moffit: The most common enemy, these are all-round average.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay3_beetle">
				<source><![CDATA[Vernax: Slow but tough! They are easy to knock off the wall, but have more resistance to melee and ranged attacks.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="howtoplay3_millipede">
				<source><![CDATA[Millipedes: These are extremely slow and tough. They are made up of many body segments, each of which must be destroyed to defeat them. They cannot be knocked off, and slowing weapons hurt them, but don't slow them.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="title1_txt">
				<source><![CDATA[Sir Liam's]]></source>
			</trans-unit>
			<trans-unit id="001" resname="title2_txt">
				<source><![CDATA[CASTLE]]></source>
			</trans-unit>
			<trans-unit id="001" resname="title3_txt">
				<source><![CDATA[DEFENDER]]></source>
			</trans-unit>
			<trans-unit id="001" resname="startTitle">
				<source><![CDATA[Get Ready!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="startBlurb">
				<source><![CDATA[Prepare for battle!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="settingsTitle">
				<source><![CDATA[Settings]]></source>
			</trans-unit>
			<trans-unit id="001" resname="quitTitle">
				<source><![CDATA[Are you sure?]]></source>
			</trans-unit>
			<trans-unit id="001" resname="quitBlurb">
				<source><![CDATA[Do you really want to quit your game?]]></source>
			</trans-unit>
			<trans-unit id="001" resname="completeTitle">
				<source><![CDATA[Game Complete]]></source>
			</trans-unit>
			<trans-unit id="001" resname="completeBlurb">
				<source><![CDATA[Congratulations my noble knight, you have defended the King's Castle with great valour. We have won the day! I hope you will help me again soon.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="playerName_lbl">
				<source><![CDATA[Player:]]></source>
			</trans-unit>
			<trans-unit id="001" resname="score_lbl">
				<source><![CDATA[Final Score:]]></source>
			</trans-unit>
			<trans-unit id="001" resname="ppPoints_lbl">
				<source><![CDATA[Park Points Awarded:]]></source>
			</trans-unit>
			<trans-unit id="001" resname="exitTitle">
				<source><![CDATA[Thanks for playing!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="exitBlurb">
				<source><![CDATA[I hope to see you at the castle again soon!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="failedTitle">
				<source><![CDATA[Level Failed]]></source>
			</trans-unit>
			<trans-unit id="001" resname="failedBlurb">
				<source><![CDATA[Tragedy! The Evil Petpetpet invaders captured the King's Flag!

But the day is not lost - try once more to vanquish these insect invaders!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="levelCompleteTitle">
				<source><![CDATA[Level Complete]]></source>
			</trans-unit>
			<trans-unit id="001" resname="finalLevelCompleteTitle">
				<source><![CDATA[Final Level Complete]]></source>
			</trans-unit>
			<trans-unit id="001" resname="finalLevelCompleteBlurb">
				<source><![CDATA[That was it! You have defeated the final wave of Petpetpets! Victory!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="levelCompleteBlurb">
				<source><![CDATA[Well done my warrior! You have repelled the cursed invaders once more! Now, we must redouble our efforts and protect the next section of the castle.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="menu_money_lbl">
				<source><![CDATA[Remaining Money & Defenders:]]></source>
			</trans-unit>
			<trans-unit id="001" resname="lives_lbl">
				<source><![CDATA[Castle Flag bonus:]]></source>
			</trans-unit>
			<trans-unit id="001" resname="windowBonus_lbl">
				<source><![CDATA[Scared Window bonus:]]></source>
			</trans-unit>
			<trans-unit id="001" resname="levelScore_lbl">
				<source><![CDATA[Level Score:]]></source>
			</trans-unit>
			<trans-unit id="001" resname="totalScore_lbl">
				<source><![CDATA[Game Score:]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderLongRange1_desc">
				<source><![CDATA[Long range, medium power.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderLongRange2_desc">
				<source><![CDATA[Increased range, power and rate of fire.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderLongRange3_desc">
				<source><![CDATA[Further increased range, power and rate of fire.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderCloseRange1_desc">
				<source><![CDATA[Very short range, powerful.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderCloseRange2_desc">
				<source><![CDATA[More powerful and higher rate of fire.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderCloseRange3_desc">
				<source><![CDATA[Very powerful and fast attacks.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderSlowing1_desc">
				<source><![CDATA[Medium range, slows <br />enemies.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderSlowing2_desc">
				<source><![CDATA[Increased range and rate of fire. Slows enemies more and for longer.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderSlowing3_desc">
				<source><![CDATA[Slows all enemies in an area, also does a small amount of damage over time.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderAreaEffect1_desc">
				<source><![CDATA[Short range, medium power, hits multiple enemies.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderAreaEffect2_desc">
				<source><![CDATA[Increased range, rate of fire and power. Also does extra damage over time.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderAreaEffect3_desc">
				<source><![CDATA[Further increased range, rate of fire and power.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderDrop1_desc">
				<source><![CDATA[Drops barrels. Hit enemies beneath and can knock off.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderDrop2_desc">
				<source><![CDATA[Drops bigger barrels more regularly. Does more damage and more likely to knock off.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderDrop3_desc">
				<source><![CDATA[Drops even bigger barrels that do more damage still and are better at knocking off.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="upgrade">
				<source><![CDATA[Upgrade]]></source>
			</trans-unit>
			<trans-unit id="001" resname="noUpgrade">
				<source><![CDATA[Upgraded]]></source>
			</trans-unit>
			<trans-unit id="001" resname="noUpgrade_desc">
				<source><![CDATA[The defender can not be upgraded any further.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="buyDescBlank">
				<source><![CDATA[Roll over a button to learn about the defender]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderLongRange1">
				<source><![CDATA[Long Range]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderSlowing1">
				<source><![CDATA[Slowing]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderDrop1">
				<source><![CDATA[Drop]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderCloseRange1">
				<source><![CDATA[Close Range]]></source>
			</trans-unit>
			<trans-unit id="001" resname="DefenderAreaEffect1">
				<source><![CDATA[Area Effect]]></source>
			</trans-unit>
			<trans-unit id="001" resname="sell">
				<source><![CDATA[Sell Defender]]></source>
			</trans-unit>
			<trans-unit id="001" resname="money_lbl">
				<source><![CDATA[Money:]]></source>
			</trans-unit>
			<trans-unit id="001" resname="level_lbl">
				<source><![CDATA[Level:]]></source>
			</trans-unit>
			<trans-unit id="001" resname="wave_lbl">
				<source><![CDATA[Wave:]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_welcome1">
				<source><![CDATA[Welcome to Castle Defender!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_welcome2">
				<source><![CDATA[The Petpetpets invaders are attacking!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_welcome3">
				<source><![CDATA[Stop them from reaching the King's Flag by placing Defenders.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_welcome4">
				<source><![CDATA[To place a Defender, click on an empty window or battlement slot, and choose from the menu.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_defender1">
				<source><![CDATA[Your Defenders will automatically attack invaders in range.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_defender2">
				<source><![CDATA[You earn money from defeating Petpetpet invaders.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_defender3">
				<source><![CDATA[With this money, you can buy more Defenders or upgrade the ones you have.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_bonus1">
				<source><![CDATA[By the way, try and keep the Petpetpets away from the yellow window...]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_bonus2">
				<source><![CDATA[The Princess doesn't like creepy crawley Petpetpets so make sure to keep them away from her! ]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_webbed">
				<source><![CDATA[Oh no - one of your Defenders has been webbed by a Aboogala! Click on him to free him!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_millipede1">
				<source><![CDATA[Get ready - the Millipede is here!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_millipede2">
				<source><![CDATA[This is the final Petpetpet in this attack - defeat it and we've won!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_upgrade1">
				<source><![CDATA[You can afford to upgrade one of your Defenders!]]></source>
			</trans-unit>
			<trans-unit id="001" resname="tip_upgrade2">
				<source><![CDATA[To upgrade a Defender, click on him and select the Upgrade option from the menu.]]></source>
			</trans-unit>
			<trans-unit id="001" resname="">
				<source><![CDATA[]]></source>
			</trans-unit>
			<trans-unit id="001" resname="">
				<source><![CDATA[]]></source>
			</trans-unit>
			<trans-unit id="001" resname="">
				<source><![CDATA[]]></source>
			</trans-unit>
			<trans-unit id="001" resname="">
				<source><![CDATA[]]></source>
			</trans-unit>
			<trans-unit id="001" resname="">
				<source><![CDATA[]]></source>
			</trans-unit>
			<trans-unit id="001" resname="">
				<source><![CDATA[]]></source>
			</trans-unit>
			<trans-unit id="001" resname="">
				<source><![CDATA[]]></source>
			</trans-unit>
			
			
			<!--<trans-unit id="001" resname="gameLogoTxt">
				<source><![CDATA[]]></source>
			</trans-unit>
			<trans-unit id="001" resname="gameLogoTxt">
				<source><![CDATA[]]></source>
			</trans-unit>
			<trans-unit id="001" resname="gameLogoTxt">
				<source><![CDATA[]]></source>
			</trans-unit>-->
		
		
		
		</body>
		<system>
			<langs>
				<lang>
					<name>English</name>
					<code>en</code>
					<enabled>1</enabled>
					<langgroup>WE</langgroup>
				</lang>
				<lang>
					<name>Nederlands</name>
					<code>nl</code>
					<enabled>0</enabled>
					<langgroup>WE</langgroup>
				</lang>
				<lang>
					<name>Portugu%C3%AAs</name>
					<code>pt</code>
					<enabled>0</enabled>
					<langgroup>WE</langgroup>
				</lang>
				<lang>
					<name>Deutsch</name>
					<code>de</code>
					<enabled>0</enabled>
					<langgroup>WE</langgroup>
				</lang>
				<lang>
					<name>Fran%C3%A7ais</name>
					<code>fr</code>
					<enabled>0</enabled>
					<langgroup>WE</langgroup>
				</lang>
				<lang>
					<name>Italiano</name>
					<code>it</code>
					<enabled>0</enabled>
					<langgroup>WE</langgroup>
				</lang>
				<lang>
					<name>Espa%C3%B1ol</name>
					<code>es</code>
					<enabled>0</enabled>
					<langgroup>WE</langgroup>
				</lang>
				<lang>
					<name>%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87</name>
					<code>ch</code>
					<enabled>0</enabled>
					<langgroup>NW</langgroup>
				</lang>
				<lang>
					<name>%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87</name>
					<code>zh</code>
					<enabled>0</enabled>
					<langgroup>NW</langgroup>
				</lang>
				<lang>
					<name>%E6%97%A5%E6%9C%AC%E8%AA%9E</name>
					<code>ja</code>
					<enabled>0</enabled>
					<langgroup>NW</langgroup>
				</lang>
				<lang>
					<name>%ED%95%9C%EA%B5%AD%EC%96%B4</name>
					<code>ko</code>
					<enabled>0</enabled>
					<langgroup>NW</langgroup>
				</lang>
			</langs>
		</system>
	</file>
</xliff>
