<!-- START xml below here -->

<?xml version='1.0' ?>
<message success = '1' text = ''>
	<action>load_response</action>
	<puzzle>
		<word box='1' dir='a' clue='How Sonny feels when he eats Cocoa Puffs' ans='SATISFIED' />
		<word box='22' dir='a' clue='Cocoa Puffs has a great _____ flavor' ans='CHOCOLATE' />
		<word box='35' dir='a' clue='&#39;Right ____ rain.&#39;' ans='AS' />
		<word box='41' dir='a' clue='Cereal ___, in Neopia Central' ans='ADVENTURE' />
		<word box='61' dir='a' clue='Frosted ___ Puffs' ans='CORN' />
		<word box='66' dir='a' clue='Cocoa Puffs is a ____ come true' ans='DREAM' />
		<word box='87' dir='a' clue='Cocoa Puffs is usually eaten in a ____' ans='BOWL' />
		<word box='91' dir='a' clue='General ____' ans='MILLS' />
		
		<word box='6' dir='d' clue='___ Corn Puffs' ans='FROSTED' />
		<word box='9' dir='d' clue='Neopets ____ com' ans='DOT' />
		<word box='23' dir='d' clue='To float' ans='HOVER' />
		<word box='25' dir='d' clue='You ____ go cuckoo, too!' ans='CAN' />
		<word box='28' dir='d' clue='What you breathe' ans='AIR' />
		<word box='31' dir='d' clue='_____ helps your bones grow strong' ans='CALCIUM' />
		<word box='64' dir='d' clue='Fluffy Petpet with large mane' ans='NOIL' />
		<word box='67' dir='d' clue='A type of gem' ans='RUBY' />
		<word box='70' dir='d' clue='Pour this on your Cocoa Puffs' ans='MILK' />
		
	</puzzle>
	
	<puzzle>
		<word box='1' dir='a' clue='Cocoa Puffs is a ____ come true' ans='DREAM' />
		<word box='18' dir='a' clue='Hooved Neopet species' ans='UNI' />
		<word box='23' dir='a' clue='Frosted ____ Puffs' ans='CORN' />
		<word box='37' dir='a' clue='Cocoa Puffs is usually eaten in a ____' ans='BOWL' />
		<word box='41' dir='a' clue='I&#39;m ___ for Cocoa Puffs!' ans='CUCKOO' />
		<word box='65' dir='a' clue='The shape of Cocoa Puffs' ans='ROUND' />
		<word box='78' dir='a' clue='Fuel for a car' ans='GAS' />
		<word box='81' dir='a' clue='How Sonny feels when he eats Cocoa Puffs' ans='SATISFIED' />
		
		<word box='1' dir='d' clue='Cocoa Puffs taste ____' ans='DELICIOUS' />
		<word box='10' dir='d' clue='General ____' ans='MILLS' />
		<word box='23' dir='d' clue='____ Puffs' ans='COCOA' />
		<word box='38' dir='d' clue='Colour of Sonny&#39;s feathers' ans='ORANGE' />
		<word box='66' dir='d' clue='Not on' ans='OFF' />
		<word box='69' dir='d' clue='Fathers' ans='DADS' />
		
	</puzzle>
	
	<puzzle>
		<word box='7' dir='a' clue='Frosted ____ Puffs' ans='CORN' />
		<word box='11' dir='a' clue='Four-legged, winged Neopets species' ans='EYRIE' />
		<word box='27' dir='a' clue='____ Negg, wears sunglasses' ans='COOL' />
		<word box='31' dir='a' clue='Sonny&#39;s friend, ___ the Leprechaun' ans='LUCKY' />
		<word box='55' dir='a' clue='Colour of the Cocoa Puffs box' ans='BROWN' />
		<word box='72' dir='a' clue='How Sonny feels when he eats Cocoa Puffs' ans='SATISFIED' />
		<word box='94' dir='a' clue='The shape of Cocoa Puffs' ans='ROUND' />
		
		<word box='1' dir='d' clue='Cocoa Puffs is part of a _____ breakfast' ans='HEALTHY' />
		<word box='4' dir='d' clue='Pour this on your Cocoa Puffs' ans='MILK' />
		<word box='7' dir='d' clue='I&#39;m ___ for Cocoa Puffs!' ans='CUCKOO' />
		<word box='29' dir='d' clue='Colour of Sonny&#39;s feathers' ans='ORANGE' />
		<word box='33' dir='d' clue='____ Puffs' ans='COCOA' />
		<word box='77' dir='d' clue='Sonny is always up to something __' ans='FUN' />
		<word box='80' dir='d' clue='Not wet' ans='DRY' />
		
	</puzzle>
	
	<puzzle>
		<word box='1' dir='a' clue='____-Tac-Toe' ans='TIC' />
		<word box='5' dir='a' clue='Space Neopet species' ans='GRUNDO' />
		<word box='27' dir='a' clue='One piece of a book' ans='PAGE' />
		<word box='31' dir='a' clue='____ Puffs' ans='COCOA' />
		<word box='47' dir='a' clue='Sonny is always up to something __' ans='FUN' />
		<word box='63' dir='a' clue='General ____' ans='MILLS' />
		<word box='93' dir='a' clue='Cocoa Puffs is a ____ come true' ans='DREAM' />
		
		<word box='3' dir='d' clue='_____ helps your bones grow strong' ans='CALCIUM' />
		<word box='5' dir='d' clue='Cocoa Puffs have a ____ chocolatey taste' ans='GREAT' />
		<word box='10' dir='d' clue='Half of two' ans='ONE' />
		<word box='27' dir='d' clue='Cocoa ____' ans='PUFFS' />
		<word box='29' dir='d' clue='____ Mills' ans='GENERAL' />
		<word box='31' dir='d' clue='Cocoa Puffs stay ____ in milk' ans='CRUNCHY' />
		<word box='65' dir='d' clue='An emotion Sonny feels for Cocoa Puffs' ans='LOVE' />
		
	</puzzle>
	
	<puzzle>
		<word box='1' dir='a' clue='The most important meal of the day' ans='BREAKFAST' />
		<word box='24' dir='a' clue='___ Corn Puffs' ans='FROSTED' />
		<word box='31' dir='a' clue='Didn&#39;t lose' ans='WON' />
		<word box='44' dir='a' clue='General ____' ans='MILLS' />
		<word box='58' dir='a' clue='Sonny is always up to something __' ans='FUN' />
		<word box='61' dir='a' clue='Cocoa Puffs is usually eaten in a ____' ans='BOWL' />
		<word box='76' dir='a' clue='Cocoa Puffs is a ____ come true' ans='DREAM' />
		<word box='91' dir='a' clue='____ helps your bones grow strong' ans='CALCIUM' />
		
		<word box='1' dir='d' clue='Colour of the Cocoa Puffs box' ans='BROWN' />
		<word box='5' dir='d' clue='Neopet species, the Island Mystic is one' ans='KYRII' />
		<word box='8' dir='d' clue='How Sonny feels when he eats Cocoa Puffs' ans='SATISFIED' />
		<word box='30' dir='d' clue='Opposite of up' ans='DOWN' />
		<word box='44' dir='d' clue='Pour this on your Cocoa Puffs' ans='MILK' />
		<word box='46' dir='d' clue='Not quiet' ans='LOUD' />
		<word box='52' dir='d' clue='____ Puffs' ans='COCOA' />
		
	</puzzle>
	
	
	
	
	<puzzle>
		<word box='1' dir='a' clue='The shape of Cocoa Puffs' ans='ROUND' />
		<word box='7' dir='a' clue='Sonny is a cuckoo ____.' ans='BIRD' />
		<word box='13' dir='a' clue='Danger' ans='PERIL' />
		<word box='24' dir='a' clue='____ Mills' ans='GENERAL' />
		<word box='32' dir='a' clue='Nimmo ____, exercise book' ans='YOGA' />
		<word box='47' dir='a' clue='Compact ____' ans='DISC' />
		<word box='61' dir='a' clue='Pleistocene: The Ice ____' ans='AGE' />
		<word box='65' dir='a' clue='I&#39;m ___ for Cocoa Puffs!' ans='CUCKOO' />
		<word box='71' dir='a' clue='Seasonal Attack ____' ans='PEA' />
		<word box='77' dir='a' clue='Not off' ans='ON' />
		<word box='82' dir='a' clue='They love to bounce on their tails' ans='BLUMAROOS' />
		<word box='95' dir='a' clue='Uncle&#39;s spouse' ans='AUNT' />
		
		<word box='1' dir='d' clue='Scarlet' ans='RED' />
		<word box='3' dir='d' clue='Opposite of down' ans='UP' />
		<word box='4' dir='d' clue='Spiked ____' ans='NEGG' />
		<word box='5' dir='d' clue='Cocoa Puffs is a ____ come true.' ans='DREAM' />
		<word box='7' dir='d' clue='To mix together' ans='BLEND' />
		<word box='10' dir='d' clue='Cocoa Puffs taste ____.' ans='DELICIOUS' />
		<word box='16' dir='d' clue='Not out' ans='IN' />
		<word box='33' dir='d' clue='A difficult experience' ans='ORDEAL' />
		<word box='41' dir='d' clue='Applaud' ans='CLAP' />
		<word box='62' dir='d' clue='Pyramid-shaped Petpets' ans='GEBS' />
		<word box='65' dir='d' clue='Deep unconsciousness' ans='COMA' />
		<word box='67' dir='d' clue='Frosted ___ Puffs' ans='CORN' />
		<word box='68' dir='d' clue='A tangle' ans='KNOT' />
		<word box='86' dir='d' clue='Symbol for gold' ans='AU' />
		
	</puzzle>
	
	<puzzle>
		<word box='1' dir='a' clue='____-O-Slime' ans='CUP' />
		<word box='5' dir='a' clue='____ Puffs!' ans='COCOA' />
		<word box='23' dir='a' clue='The best utensils for Cocoa Puffs' ans='SPOONS' />
		<word box='31' dir='a' clue='Type of Mote' ans='ASH' />
		<word box='44' dir='a' clue='____ Fontaines Perfect Pizza' ans='LORETTA' />
		<word box='62' dir='a' clue='The most important meal of the day.' ans='BREAKFAST' />
		<word box='71' dir='a' clue='____ Snorkle, a shiny Petpet' ans='ROBOT' />
		<word box='78' dir='a' clue='Exclamation - Oops!' ans='DOH' />
		<word box='81' dir='a' clue='____ shucks!' ans='AW' />
		<word box='84' dir='a' clue='&#39;Visit the Negg Faerie&#39;' ans='NEGGERY' />
		<word box='91' dir='a' clue='Two ___ one equals three' ans='PLUS' />
		<word box='97' dir='a' clue='Lyric poem' ans='ODE' />
		
		<word box='1' dir='d' clue='Chokato ___ Pop' ans='CHIA' />
		<word box='3' dir='d' clue='Shove' ans='PUSH' />
		<word box='5' dir='d' clue='Cocoa Puffs has a great _____ flavour' ans='CHOCOLATE' />
		<word box='7' dir='d' clue='Small boat with pointed ends' ans='CANOE' />
		<word box='30' dir='d' clue='Cocoa Puffs is part of a _____ breakfast' ans='HEALTHY' />
		<word box='48' dir='d' clue='Exchanged' ans='TRADED' />
		<word box='53' dir='d' clue='Jerdana&#39;s ____' ans='ORB' />
		<word box='62' dir='d' clue='Cocoa Puffs is usually eaten in a ____' ans='BOWL' />
		<word box='64' dir='d' clue='Very long periods of time' ans='EONS' />
		<word box='69' dir='d' clue='Hurting' ans='SORE' />
		<word box='71' dir='d' clue='Hip hop' ans='RAP' />
		<word box='87' dir='d' clue='Don&#39;t stop!' ans='GO' />
		
	</puzzle>
	
	<puzzle>
		<word box='1' dir='a' clue='&#39;____ upon a star&#39;' ans='WISH' />
		<word box='13' dir='a' clue='60 minutes' ans='HOUR' />
		<word box='18' dir='a' clue='To ____, or not to ____' ans='BE' />
		<word box='21' dir='a' clue='The best utensil for Cocoa Puffs' ans='SPOON' />
		<word box='27' dir='a' clue='Cereal is usually eaten out of a ____' ans='BOWL' />
		<word box='31' dir='a' clue='Insect-like Robot Petpet' ans='POPPIT' />
		<word box='41' dir='a' clue='____ far, ____ good!' ans='SO' />
		<word box='52' dir='a' clue='Pyramid-shaped Petpet' ans='GEB' />
		<word box='57' dir='a' clue='An emotion Sonny feels for Cocoa Puffs' ans='LOVE' />
		<word box='61' dir='a' clue='Slimy trail leaving Petpet' ans='SLORG' />
		<word box='71' dir='a' clue='____ Olde Petpets' ans='YE' />
		<word box='77' dir='a' clue='Candy Floss ____ Pop' ans='CHIA' />
		<word box='87' dir='a' clue='&#39;Grumpy Old ____&#39;' ans='KING' />
		<word box='91' dir='a' clue='Cocoa Puffs stay ____ in milk' ans='CRUNCHY' />
		
		<word box='1' dir='d' clue='Stinging insects' ans='WASPS' />
		<word box='3' dir='d' clue='____ Wizard' ans='SHOP' />
		<word box='4' dir='d' clue='Basketball goal' ans='HOOP' />
		<word box='9' dir='d' clue='Not old' ans='NEW' />
		<word box='15' dir='d' clue='Hooved Neopet species' ans='UNI' />
		<word box='18' dir='d' clue='Cocoa Puffs come in this' ans='BOX' />
		<word box='22' dir='d' clue='____ Racers' ans='POOGLE' />
		<word box='30' dir='d' clue='Jeran is one' ans='LUPE' />
		<word box='53' dir='d' clue='Codestone type' ans='EO' />
		<word box='54' dir='d' clue='Colour of the Cocoa Puffs box' ans='BROWN' />
		<word box='57' dir='d' clue='Sonny&#39;s friend, ___ the Leprechaun' ans='LUCKY' />
		<word box='59' dir='d' clue='Conceited' ans='VAIN' />
		<word box='61' dir='d' clue='Synchronize, e.g.' ans='SYNC' />
		<word box='78' dir='d' clue='Hello!' ans='HI' />
		<word box='80' dir='d' clue='How old you are' ans='AGE' />
		
	</puzzle>
	
	<puzzle>
		<word box='5' dir='a' clue='Colour of Sonny&#39;s feathers' ans='ORANGE' />
		<word box='11' dir='a' clue='Species of Edna the witch' ans='ZAFARA' />
		<word box='18' dir='a' clue='European Union, abbr.' ans='EU' />
		<word box='27' dir='a' clue='The ____berry is black with white specks' ans='VOID' />
		<word box='43' dir='a' clue='___ Corn Puffs' ans='FROSTED' />
		<word box='53' dir='a' clue='Codestone type' ans='LU' />
		<word box='61' dir='a' clue='The shape of Cocoa Puffs' ans='ROUND' />
		<word box='67' dir='a' clue='Pour this on your Cocoa Puffs' ans='MILK' />
		<word box='81' dir='a' clue='To clean' ans='WASH' />
		<word box='87' dir='a' clue='Wand of Dark ____' ans='NOVA' />
		<word box='91' dir='a' clue='Most popular Neopets' ans='SHOYRUS' />
		
		<word box='1' dir='d' clue='Russian ruler' ans='CZAR' />
		<word box='3' dir='d' clue='Not on' ans='OFF' />
		<word box='5' dir='d' clue='Codestone type' ans='ORN' />
		<word box='6' dir='d' clue='Egyptian sun god' ans='RA' />
		<word box='8' dir='d' clue='____points' ans='NEO' />
		<word box='9' dir='d' clue='A club for friends on Neopets' ans='GUILD' />
		<word box='27' dir='d' clue='Nutrients that help you stay healthy' ans='VITAMINS' />
		<word box='34' dir='d' clue='Cocoa Puffs stay ____ in milk' ans='CRUNCHY' />
		<word box='43' dir='d' clue='Neo ____, cured with special jelly pills' ans='FLU' />
		<word box='61' dir='d' clue='Uses oars' ans='ROWS' />
		<word box='69' dir='d' clue='An emotion Sonny feels for Cocoa Puffs' ans='LOVE' />
		<word box='82' dir='d' clue='Eureka! : &#39;____ ha!&#39;' ans='AH' />
		<word box='83' dir='d' clue='____ far, ____ good!' ans='SO' />
		
	</puzzle>
	
	<puzzle>
		<word box='1' dir='a' clue='Not down' ans='ACROSS' />
		<word box='18' dir='a' clue='A wing, to a fish' ans='FIN' />
		<word box='23' dir='a' clue='_____ helps your bones grow strong' ans='CALCIUM' />
		<word box='51' dir='a' clue='Cereal ___, in Neopia Central' ans='ADVENTURE' />
		<word box='72' dir='a' clue='Petpet that loves to fetch!' ans='PUPPYBLEW' />
		<word box='81' dir='a' clue='Stack' ans='PILE' />
		<word box='91' dir='a' clue='&#39;The Joy of ____ Work&#39;' ans='METAL' />
		<word box='97' dir='a' clue='Pour this on your Cocoa Puffs' ans='MILK' />
		
		<word box='4' dir='d' clue='Colour of Sonny&#39;s feathers' ans='ORANGE' />
		<word box='6' dir='d' clue='Covertly, hidden from sight' ans='SECRETLY' />
		<word box='9' dir='d' clue='Not bright' ans='DIM' />
		<word box='18' dir='d' clue='Sonny is always up to something __' ans='FUN' />
		<word box='21' dir='d' clue='Cocoa Puffs have a _______ chocolatey taste' ans='GREAT' />
		<word box='49' dir='d' clue='Breakfast ___ ' ans='CEREAL' />
		<word box='53' dir='d' clue='Bank ____, like a very large safe' ans='VAULT' />
		<word box='72' dir='d' clue='Lenny Meringue ____, served by the slice' ans='PIE' />
		<word box='74' dir='d' clue='Seasonal Attack ____' ans='PEA' />
		<word box='81' dir='d' clue='Time of day when it isn&#39;t A.M.' ans='PM' />
		
	</puzzle>
</message>

<!-- END xml above here -->
