# @(#)font.properties	1.4 97/03/03. Modified 11/24/97.
#
# AWT Font default Properties for Windows 95/NT 
#

dialog.0=Arial,ANSI_CHARSET
dialog.1=Bitstream Cyberbit, DEFAULT_CHARSET
dialog.2=MS Gothic,SHIFTJIS_CHARSET
dialog.3=WingDings,SYMBOL_CHARSET,NEED_CONVERTED
dialog.4=Symbol,SYMBOL_CHARSET,NEED_CONVERTED

dialoginput.0=Courier New,ANSI_CHARSET
dialoginput.1=Bitstream Cyberbit,DEFAULT_CHARSET
dialoginput.2=MS Gothic,SHIFTJIS_CHARSET
dialoginput.3=WingDings,SYMBOL_CHARSET,NEED_CONVERTED
dialoginput.4=Symbol,SYMBOL_CHARSET,NEED_CONVERTED

serif.0=Times New Roman,ANSI_CHARSET
serif.1=Bitstream Cyberbit,DEFAULT_CHARSET
serif.2=MS Gothic,SHIFTJIS_CHARSET
serif.3=WingDings,SYMBOL_CHARSET,NEED_CONVERTED
serif.4=Symbol,SYMBOL_CHARSET,NEED_CONVERTED

sansserif.0=Arial,ANSI_CHARSET
sansserif.1=Bitstream Cyberbit,DEFAULT_CHARSET
sansserif.2=MS Gothic,SHIFTJIS_CHARSET
sansserif.3=WingDings,SYMBOL_CHARSET,NEED_CONVERTED
sansserif.4=Symbol,SYMBOL_CHARSET,NEED_CONVERTED

monospaced.0=Courier New,ANSI_CHARSET
monospaced.1=Bitstream Cyberbit,DEFAULT_CHARSET
monospaced.2=MS Gothic,SHIFTJIS_CHARSET
monospaced.3=WingDings,SYMBOL_CHARSET,NEED_CONVERTED
monospaced.4=Symbol,SYMBOL_CHARSET,NEED_CONVERTED

# name aliases
#
# alias.timesroman=serif
# alias.helvetica=sansserif
# alias.courier=monospaced

# for backword compatibility
timesroman.0=Times New Roman,ANSI_CHARSET
timesroman.1=Bitstream Cyberbit,DEFAULT_CHARSET
timesroman.2=MS Gothic,SHIFTJIS_CHARSET
helvetica.0=Arial,ANSI_CHARSET
helvetica.1=Bitstream Cyberbit,DEFAULT_CHARSET
helvetica.2=MS Gothic,SHIFTJIS_CHARSET
courier.0=Courier New,ANSI_CHARSET
courier.1=Bitstream Cyberbit,DEFAULT_CHARSET
courier.2=MS Gothic,SHIFTJIS_CHARSET
zapfdingbats.0=WingDings,SYMBOL_CHARSET

# Default font definition
#
default.char=2751

# Static FontCharset info.
#
fontcharset.dialog.3=sun.awt.windows.CharToByteWingDings
fontcharset.dialog.4=sun.awt.CharToByteSymbol

fontcharset.dialoginput.3=sun.awt.windows.CharToByteWingDings
fontcharset.dialoginput.4=sun.awt.CharToByteSymbol

fontcharset.serif.3=sun.awt.windows.CharToByteWingDings
fontcharset.serif.4=sun.awt.CharToByteSymbol

fontcharset.sansserif.3=sun.awt.windows.CharToByteWingDings
fontcharset.sansserif.4=sun.awt.CharToByteSymbol

fontcharset.monospaced.3=sun.awt.windows.CharToByteWingDings
fontcharset.monospaced.4=sun.awt.CharToByteSymbol

# Exclusion Range info.
#
exclusion.dialog.0=0100-ffff

exclusion.dialoginput.0=0100-ffff

exclusion.serif.0=0100-ffff

exclusion.sansserif.0=0100-ffff

exclusion.monospaced.0=0100-ffff

# charset for text input
#
inputtextcharset=ANSI_CHARSET

