<!DOCTYPE xliff PUBLIC "-//XLIFF//DTD XLIFF//EN"
 "http://www.oasis-open.org/committees/xliff/documents/xliff.dtd" >
<xliff version="1.0" xml:lang="en">
 <file datatype="plaintext" original="900102" source-language="EN">
  <header></header>
  <body>
<trans-unit id="001" resname="TRANSLATION_TITLE">
<source>Comic%20Pages%3A%20Haunted%20Woods%2C%20Prologue%20Pt.%202</source>
</trans-unit>
<trans-unit id="002" resname="IDS_PREVIOUS_PAGE">
<source>%3Cp%20align%3D%27left%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3EBack%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="003" resname="IDS_NEXT_PAGE">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3ENext%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="004" resname="IDS_BOOK2_PAGE1_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AAs%20the%20days%20passed%2C%20however%2C%20the%20potions%20began%20to%20reveal%20the%20darker%20side%20of%20their%20ambitions.%20%20Edmund%20grew%20miserly%20with%20his%20newfound%20fortune%20and%20became%20suspicious%20of%20everyone%20around%20him.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="005" resname="IDS_BOOK2_PAGE1_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ABruno%27s%20strength%20continued%20to%20grow%20until%20he%20was%20no%20longer%20a%20handsome%20Gelert%20but%20a%20revoltingly%20muscular%20creature%20of%20grotesque%20shape%20and%20form.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="006" resname="IDS_BOOK2_PAGE1_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AReginald%20soon%20found%20that%20he%20had%20acquired%20such%20a%20vast%20intellect%20that%20no%20Neopet%20could%20follow%20his%20conversation%20anymore%2C%20leaving%20him%20to%20take%20lonely%20refuge%20among%20his%20books.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="007" resname="IDS_BOOK2_PAGE1_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ATheir%20fellow%20townspeople%20were%20undergoing%20a%20similar%20change.%20%20They%20found%20their%20greed%20and%20ambitions%20taking%20on%20horribly%20twisted%20forms%2C%20turning%20them%20into%20something%20far%20worse%20than%20they%20had%20ever%20dreamed.%20%20The%20ecstatic%20delight%20that%20had%20settled%20over%20Neovia%20soon%20vanished%20as%20quickly%20as%20it%20had%20come.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="008" resname="IDS_BOOK2_PAGE1_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AAt%20first%2C%20they%20clamoured%20for%20the%20stranger%27s%20head%2C%20intending%20to%20demand%20to%20know%20what%20his%20potions%20had%20done%20to%20them%2C%20but%20he%27d%20vanished%20as%20if%20he%20had%20never%20existed.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="009" resname="IDS_BOOK2_PAGE1_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ADesperate%20to%20find%20someone%20to%20blame%2C%20they%20turned%20on%20Edmund%20and%20his%20family%2C%20claiming%20that%20they%20were%20at%20fault%20for%20first%20advertising%20the%20elixir.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="010" resname="IDS_BOOK2_PAGE1_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThe%20family%20found%20themselves%20subjected%20to%20scorn%20and%20hatred.%20%20Even%20those%20they%20had%20formerly%20called%20friends%20were%20now%20their%20attackers.%20%20Stricken%20with%20the%20grief%20of%20betrayal%2C%20they%20retreated%20into%20their%20home%20to%20escape%20the%20crowd%27s%20wrath.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="011" resname="IDS_BOOK2_PAGE1_TEXT8_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ASeeing%20that%20their%20little%20sister%20seemed%20to%20be%20the%20only%20one%20unaffected%20by%20the%20madness%20gripping%20the%20town%2C%20Bruno%20asked%20Reginald%20to%20take%20her%20and%20flee%20into%20the%20Haunted%20Woods%2C%20where%20she%20could%20hide%20somewhere%20safe%20until%20the%20danger%20had%20passed.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="012" resname="IDS_BOOK2_PAGE1_TEXT9_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AAs%20Bruno%20tried%20to%20create%20a%20distraction%2C%20they%20managed%20to%20escape%20the%20angry%20mob%27s%20notice%20as%20they%20slipped%20into%20the%20darkness%20of%20the%20Haunted%20Woods...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="013" resname="IDS_BOOK2_PAGE2_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThe%20two%20young%20Neopets%20wandered%20into%20the%20mazelike%20woods%2C%20hostile%20even%20to%20longtime%20residents.%20%20At%20every%20turn%2C%20tree%20branches%20seemed%20to%20reach%20for%20them%20and%20bewilder%20their%20senses%2C%20trapping%20them%20in%20a%20labyrinth%20of%20twists%20and%20turns.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="014" resname="IDS_BOOK2_PAGE2_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThen%20help%20came%20upon%20them%20from%20a%20very%20unexpected%20direction...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="015" resname="IDS_BOOK2_PAGE2_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThe%20mysterious%20earth%20faerie%20Ilere%2C%20a%20figure%20from%20ghost%20stories%20told%20by%20children%20of%20the%20woods%20to%20frighten%20each%20other%2C%20appeared%20before%20them.%20%20Yet%20like%20many%20legends%2C%20she%20was%20not%20quite%20the%20terrifying%20phantom%20the%20children%20had%20imagined%20when%20they%20whispered%20tales%20of%20her%20in%20hushed%20voices%20at%20night.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="016" resname="IDS_BOOK2_PAGE2_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThere%20is%20no%20other%20refuge%20for%20her.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="017" resname="IDS_BOOK2_PAGE2_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AIt%27s%20all%20right%2C%20brother.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="018" resname="IDS_BOOK2_PAGE2_TEXT5_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%20feel%20safe%20with%20her.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="019" resname="IDS_BOOK2_PAGE2_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThough%20unwilling%20to%20let%20his%20little%20sister%20leave%20his%20care%2C%20Reginald%20relented%2C%20for%20he%20believed%20there%20was%20no%20other%20way.%20%20He%20watched%20unhappily%20as%20she%20left%20with%20the%20faerie%2C%20before%20turning%20his%20steps%20back%20toward%20Neovia%20to%20help%20the%20rest%20of%20his%20family...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="020" resname="IDS_BOOK2_PAGE2_TEXT6_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ATo%20be%20continued...%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
  </body>
  <system>
   <langs>
    <lang>
     <name>English</name>
     <code>en</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Nederlands</name>
     <code>nl</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Portugu%C3%AAs</name>
     <code>pt</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Deutsch</name>
     <code>de</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Fran%C3%A7ais</name>
     <code>fr</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Italiano</name>
     <code>it</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Espa%C3%B1ol</name>
     <code>es</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87</name>
     <code>ch</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87</name>
     <code>zh</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E6%97%A5%E6%9C%AC%E8%AA%9E</name>
     <code>ja</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%ED%95%9C%EA%B5%AD%EC%96%B4</name>
     <code>ko</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
   </langs>
  </system>
 </file>
</xliff>