<!DOCTYPE xliff PUBLIC "-//XLIFF//DTD XLIFF//EN"
 "http://www.oasis-open.org/committees/xliff/documents/xliff.dtd" >
<xliff version="1.0" xml:lang="en">
 <file datatype="plaintext" original="900103" source-language="EN">
  <header></header>
  <body>
<trans-unit id="001" resname="TRANSLATION_TITLE">
<source>Comic%20Pages%3A%20Haunted%20Woods%2C%20Prologue%20Pt.%203</source>
</trans-unit>
<trans-unit id="002" resname="IDS_PREVIOUS_PAGE">
<source>%3Cp%20align%3D%27left%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3EBack%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="003" resname="IDS_NEXT_PAGE">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3ENext%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="004" resname="IDS_BOOK3_PAGE1_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AMeanwhile%2C%20back%20in%20Neovia%2C%20the%20townspeople%27s%20anger%20had%20reached%20a%20fever%20pitch.%20%20In%20their%20fury%2C%20they%20attempted%20to%20get%20past%20Bruno%20and%20break%20into%20the%20house%2C%20but%20he%20bravely%20stood%20his%20ground.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="005" resname="IDS_BOOK3_PAGE1_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0APushed%20to%20the%20brink%2C%20the%20mob%20turned%20its%20wrath%20upon%20Bruno.%20%20As%20Edmund%20and%20Alice%20cowered%20in%20their%20house%2C%20terrified%2C%20they%20could%20only%20listen%20as%20their%20eldest%20son%20was%20attacked%20and%20driven%20from%20the%20place%20where%20he%20had%20grown%20up.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="006" resname="IDS_BOOK3_PAGE1_TEXT2_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThis%20is%20all%20his%20fault%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="007" resname="IDS_BOOK3_PAGE1_TEXT2_BUBBLE3">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AGet%20him%21%21%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="008" resname="IDS_BOOK3_PAGE1_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AReginald%20returned%20to%20Neovia%20just%20in%20time%20to%20see%20his%20brother%20chased%20out%20by%20the%20townsfolk%2C%20but%20all%20he%20could%20do%20was%20watch%20helplessly%20as%20they%20disappeared%20into%20the%20dark%20forest.%20%20He%20waited%20until%20the%20townspeople%20had%20all%20gone%20and%20then%20made%20his%20way%20back%20to%20the%20house.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="009" resname="IDS_BOOK3_PAGE1_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AQuickly%2C%20he%20found%20his%20parents%20and%20urged%20them%20to%20find%20safety.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="010" resname="IDS_BOOK3_PAGE1_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AReginald%20hurried%20his%20parents%20to%20an%20old%20abandoned%20mansion%20across%20town.%20%20As%20a%20child%2C%20he%20had%20played%20hide-and-seek%20there%20and%20knew%20it%20contained%20many%20secret%20rooms%20and%20passages.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="011" resname="IDS_BOOK3_PAGE1_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AAfter%20losing%20Bruno%20in%20the%20maze%20of%20the%20woods%2C%20the%20townspeople%20returned%20to%20Neovia%20to%20search%20for%20the%20rest%20of%20the%20family.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="012" resname="IDS_BOOK3_PAGE1_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AUnable%20to%20discover%20the%20whereabouts%20of%20Edmund%20and%20his%20family%2C%20the%20Neovians%20turned%20against%20one%20another.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="013" resname="IDS_BOOK3_PAGE1_TEXT8_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThe%20chaos%20escalated%20until%20the%20townsfolk%20began%20to%20fight%20with%20one%20another.%20%20The%20situation%20might%20have%20disintegrated%20into%20rioting%20at%20that%20point%2C%20but%20at%20the%20last%20moment%2C%20as%20the%20town%20teetered%20on%20the%20brink%20of%20insanity%2C%20the%20Mayor%20of%20Neovia%20stepped%20in%20and%20took%20control.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="014" resname="IDS_BOOK3_PAGE1_TEXT8_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ASTOP%21%21%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="015" resname="IDS_BOOK3_PAGE2_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ACitizens%20of%20Neovia%2C%20we%20must%20remain%20calm%21%20%20The%20time%20for%20blame%20has%20passed.%20%20There%20will%20be%20an%20opportunity%20for%20retribution%20later.%20%20For%20now%2C%20we%20must%20work%20together%20if%20we%20are%20to%20solve%20this.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="016" resname="IDS_BOOK3_PAGE2_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AWe%20have%20been%20cursed%20by%20magic%2C%20so%20we%20must%20be%20cured%20by%20magic%21%20%20I%20propose%20that%20we%20summon%20the%20Spirit%20of%20Slumber%21%20%20He%20haunts%20these%20very%20woods%20and%20may%20be%20able%20to%20help%20us.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="017" resname="IDS_BOOK3_PAGE2_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ADesperate%20for%20guidance%2C%20the%20townsfolk%20gathered%20together%20and%20summoned%20the%20Spirit.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="018" resname="IDS_BOOK3_PAGE2_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThe%20Spirit%20of%20Slumber%20appeared%20and%20instantly%20realised%20the%20dire%20situation.%20%20He%20told%20them%20that%20he%20could%20end%20their%20suffering%2C%20but%20the%20price%20would%20be%20terrible.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="019" resname="IDS_BOOK3_PAGE2_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ANevertheless%2C%20the%20Mayor%20agreed%20to%20the%20terms%2C%20and%20the%20curse%20was%20lifted...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="020" resname="IDS_BOOK3_PAGE2_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0A...but%20it%20did%20indeed%20come%20with%20a%20terrible%20price.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="021" resname="IDS_BOOK3_PAGE2_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThat%27s%20a%20fascinating%20story%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="022" resname="IDS_BOOK3_PAGE2_TEXT7_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AAs%20are%20most%20legends.%20%20Now%20off%20to%20bed%20with%20you%2C%20child%3B%20it%27s%20getting%20late%21%09%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="023" resname="IDS_BOOK3_PAGE2_TEXT8_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThe%20next%20morning%2C%20when%20the%20first%20rays%20of%20sunlight%20had%20struggled%20through%20the%20thick%20overhang%20of%20tree%20branches%2C%20Gilly%20thanked%20the%20gypsy%20for%20his%20hospitality%20and%20set%20off%20once%20more%20into%20the%20woods...%3C%2Ffont%3E</source>
</trans-unit>
  </body>
  <system>
   <langs>
    <lang>
     <name>English</name>
     <code>en</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Nederlands</name>
     <code>nl</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Portugu%C3%AAs</name>
     <code>pt</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Deutsch</name>
     <code>de</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Fran%C3%A7ais</name>
     <code>fr</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Italiano</name>
     <code>it</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Espa%C3%B1ol</name>
     <code>es</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87</name>
     <code>ch</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87</name>
     <code>zh</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E6%97%A5%E6%9C%AC%E8%AA%9E</name>
     <code>ja</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%ED%95%9C%EA%B5%AD%EC%96%B4</name>
     <code>ko</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
   </langs>
  </system>
 </file>
</xliff>