<!DOCTYPE xliff PUBLIC "-//XLIFF//DTD XLIFF//EN"
 "http://www.oasis-open.org/committees/xliff/documents/xliff.dtd" >
<xliff version="1.0" xml:lang="en">
 <file datatype="plaintext" original="900104" source-language="EN">
  <header></header>
  <body>
<trans-unit id="001" resname="TRANSLATION_TITLE">
<source>Comic%20Pages%3A%20Haunted%20Woods%2C%20Chapter%201</source>
</trans-unit>
<trans-unit id="002" resname="IDS_PREVIOUS_PAGE">
<source>%3Cp%20align%3D%27left%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3EBack%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="003" resname="IDS_NEXT_PAGE">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3ENext%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="004" resname="IDS_BOOK4_PAGE1_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%20wonder%20what%20lies%20that%20way...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="005" resname="IDS_BOOK4_PAGE1_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ASo%20this%20must%20be%20Neovia.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="006" resname="IDS_BOOK4_PAGE1_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AWhat%27s%20this%3F%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="007" resname="IDS_BOOK4_PAGE1_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AExcuse%20me%2C%20I%20was%20wondering%20if%20you%20could%20tell%20me%20anything%20about%20this%20locket.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="008" resname="IDS_BOOK4_PAGE1_TEXT6_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AWhy%2C%20certainly%2C%20little%20miss...%20Well%2C%20what%20a%20pretty%20little%20trinket%20this%20is.%20%20I%20haven%27t%20seen%20one%20like%20it%20in%20years.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="009" resname="IDS_BOOK4_PAGE1_TEXT6_BUBBLE3">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%20realize%20this%20is%20unlikely%2C%20but%20do%20you%20perhaps%20know%20anything%20about%20its%20owner%3F%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="010" resname="IDS_BOOK4_PAGE1_TEXT6_BUBBLE4">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%20couldn%27t%20say.%20%20They%20used%20to%20make%20a%20lot%20of%20lockets%20like%20that%2C%20but%20these%20days...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="011" resname="IDS_BOOK4_PAGE1_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AWell%2C%20it%27s%20clear%20no%20one%20around%20here%20is%20going%20to%20help%20me.%20%20I%20wonder%20if%20there%20might%20be%20someone%20deeper%20in%20the%20woods%20who%20could%20identify%20this%20locket.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="012" resname="IDS_BOOK4_PAGE1_TEXT8_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AHello%3F%20%20Is%20anyone%20home%3F%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="013" resname="IDS_BOOK4_PAGE1_TEXT9_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AUmm...%20hello%3F%20%20I...%20I%27m%20Gilly.%20%20I%20w-was%20wondering%20if%20I%20could%20ask%20you%20some%20q-questions%3F%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="014" resname="IDS_BOOK4_PAGE2_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%20hear%20there%27s%20a%20town...%20with%20a%20curse...%20and%20I%20thought%20you%20might%20know%20something%20about%20it.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="015" resname="IDS_BOOK4_PAGE2_TEXT1_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThere%20are%20lots%20of%20crazy%20myths%20about%20these%20woods%2C%20kid.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="016" resname="IDS_BOOK4_PAGE2_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ABut%20I%27ve%20seen%20proof%21%20%20Neopets%20used%20to%20live%20there%2C%20and%20now%20there%27s%20no%20one%20in%20it%21%20%20Is%20it%20true%20there%20was%20a%20potion%3F%20%20Was%20there%20really%20a%20fami-%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="017" resname="IDS_BOOK4_PAGE2_TEXT2_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AAll%20right%2C%20kid%2C%20that%27s%20enough.%20%20Get%20lost%3B%20I%27m%20busy.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="018" resname="IDS_BOOK4_PAGE2_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%20have%20a%20locket%20here%20that%20I%20found%3B%20I%20think%20it%20may%20be%20a%20clue.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="019" resname="IDS_BOOK4_PAGE2_TEXT3_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AWhere%20did%20you%20get%20that%3F%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="020" resname="IDS_BOOK4_PAGE2_TEXT3_BUBBLE3">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AIn%20the%20town%21%20%20There%27s%20something%20mysterious%20about%20that%20place-%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="021" resname="IDS_BOOK4_PAGE2_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ALook%2C%20little%20girl%2C%20I%20should%27ve%20turned%20you%20into%20a%20stink%20beetle%20the%20moment%20you%20interrupted%20me%2C%20but%20I%20was%20too%20nice.%20%20If%20you%27re%20not%20out%20of%20here%20in%20three%20seconds%2C%20I%27ll%20be%20sure%20to%20fix%20that.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="022" resname="IDS_BOOK4_PAGE2_TEXT4_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AWait%2C%20please%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="023" resname="IDS_BOOK4_PAGE2_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ASLAM%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="024" resname="IDS_BOOK4_PAGE2_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThree...%20two...%20%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="025" resname="IDS_BOOK4_PAGE2_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%20have%20to%20find%20shelter%20before%20this%20storm%20gets%20worse.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="026" resname="IDS_BOOK4_PAGE2_TEXT10_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0A%0AGrrrrrrrrrrrrrrrrrrr...%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
  </body>
  <system>
   <langs>
    <lang>
     <name>English</name>
     <code>en</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Nederlands</name>
     <code>nl</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Portugu%C3%AAs</name>
     <code>pt</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Deutsch</name>
     <code>de</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Fran%C3%A7ais</name>
     <code>fr</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Italiano</name>
     <code>it</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Espa%C3%B1ol</name>
     <code>es</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87</name>
     <code>ch</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87</name>
     <code>zh</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E6%97%A5%E6%9C%AC%E8%AA%9E</name>
     <code>ja</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%ED%95%9C%EA%B5%AD%EC%96%B4</name>
     <code>ko</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
   </langs>
  </system>
 </file>
</xliff>