<!DOCTYPE xliff PUBLIC "-//XLIFF//DTD XLIFF//EN"
 "http://www.oasis-open.org/committees/xliff/documents/xliff.dtd" >
<xliff version="1.0" xml:lang="en">
 <file datatype="plaintext" original="900101" source-language="EN">
  <header></header>
  <body>
<trans-unit id="001" resname="TRANSLATION_TITLE">
<source>Comic%20Pages%3A%20Haunted%20Woods%2C%20Prologue%20Pt.%201</source>
</trans-unit>
<trans-unit id="002" resname="IDS_PREVIOUS_PAGE">
<source>%3Cp%20align%3D%27left%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3EBack%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="003" resname="IDS_NEXT_PAGE">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3ENext%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="004" resname="IDS_BOOK1_PAGE1_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AOn%20one%20of%20the%20many%20shadowy%20nights%20that%20shroud%20the%20Haunted%20Woods%2C%20a%20lost%20traveller%20named%20Gilly%20wandered%20in%20the%20darkness.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="005" resname="IDS_BOOK1_PAGE1_TEXT1_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AIt%27s%20nightfall%20already%2C%20and%20I%20still%20have%20no%20idea%20where%20I%20am.%20Why%20does%20this%20always%20happen%20to%20me%3F%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="006" resname="IDS_BOOK1_PAGE1_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AJust%20as%20she%20began%20to%20think%20that%20she%20would%20never%20find%20shelter%2C%20she%20spotted%20a%20speck%20of%20firelight%2C%20flickering%20warmly%20in%20the%20distance.%20Quickly%2C%20she%20hurried%20towards%20the%20fragment%20of%20hope.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="007" resname="IDS_BOOK1_PAGE1_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AWhy%2C%20come%20here%2C%20child%3B%20you%27re%20shivering.%20Take%20a%20seat%20by%20the%20fire.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="008" resname="IDS_BOOK1_PAGE1_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThank%20you%20so%20much%2C%20sir.%20I%20swear%20I%20was%20on%20the%20correct%20path%2C%20but%20I%20must%20have%20taken%20a%20wrong%20turn...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="009" resname="IDS_BOOK1_PAGE1_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AIt%27s%20dangerous%20to%20get%20lost%20in%20these%20woods.%20Trees%20and%20creatures%20roam%20the%20night%2C%20and%20they%20can%20swallow%20the%20unwary.%20It%27s%20no%20accident%20that%20so%20many%20legends%20and%20myths%20surround%20this%20place%3B%20in%20fact%2C%20I%20was%20reading%20about%20one%20just%20now.%20Would%20you%20like%20to%20hear%20about%20it%3F%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="010" resname="IDS_BOOK1_PAGE1_TEXT5_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AOh%20yes%2C%20please%21%20I%20love%20those%20stories.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="011" resname="IDS_BOOK1_PAGE1_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AIt%20began%20with%20an%20ordinary%20family%20in%20an%20ordinary%20town.%20Neovia%20was%20a%20quaint%20little%20place%2C%20tucked%20away%20in%20the%20corner%20of%20the%20Haunted%20Woods.%20Here%20in%20this%20relative%20peace%20and%20quiet%20lived%20Edmund%2C%20Alice%2C%20and%20their%20three%20children.%20Like%20every%20family%2C%20they%20had%20their%20problems...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="012" resname="IDS_BOOK1_PAGE2_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ATheir%20eldest%20son%20was%20Bruno%2C%20a%20painfully%20shy%20young%20Gelert%20who%20only%20had%20eyes%20for%20one%20Neopet%20in%20town...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="013" resname="IDS_BOOK1_PAGE2_TEXT1_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AHi%2C%20Lily.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="014" resname="IDS_BOOK1_PAGE2_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AHey%21%20What%20do%20you%20think%20you%27re%20doing%3F%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="015" resname="IDS_BOOK1_PAGE2_TEXT2_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AOscar%2C%20please%2C%20leave%20him%20alone...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="016" resname="IDS_BOOK1_PAGE2_TEXT2_BUBBLE3">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ANo%2C%20this%20little%20twerp%20needs%20to%20learn%20not%20to%20mess%20with%20my%20girl%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="017" resname="IDS_BOOK1_PAGE2_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2720%27%3E%0ACRACK%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="018" resname="IDS_BOOK1_PAGE2_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AOscar%2C%20no%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="019" resname="IDS_BOOK1_PAGE2_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThat%20should%20teach%20him.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="020" resname="IDS_BOOK1_PAGE2_TEXT5_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AUnfortunately%2C%20he%20had%20neither%20the%20charm%20nor%20the%20strength%20to%20win%20her%20affections.%20Bruno%20had%20always%20felt%20awkward%20and%20lonely%2C%20and%20it%20seemed%20to%20him%20that%20he%20would%20always%20remain%20this%20way.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="021" resname="IDS_BOOK1_PAGE2_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ADisheartened%20and%20miserable%2C%20Bruno%20had%20resigned%20himself%20to%20his%20fate%2C%20when%20that%20same%20fate%20took%20a%20sudden%20turn%20for%20him...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="022" resname="IDS_BOOK1_PAGE2_TEXT6_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AYou%20look%20troubled.%20Perhaps%20I%20can%20be%20of%20assistance...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="023" resname="IDS_BOOK1_PAGE2_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%20have%20here%20an%20elixir%2C%20proven%20to%20chase%20away%20all%20sorrows%20and%20fulfill%20all%20desires.%20Whatever%20you%20want%20in%20life%2C%20it%20will%20grant.%20I%20only%20ask%20for%20a%20handful%20of%20Neopoints%20in%20recompense.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="024" resname="IDS_BOOK1_PAGE2_TEXT7_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AA%20stranger%20approached%20Bruno%20and%20offered%20to%20make%20all%20his%20wishes%20come%20true.%20The%20young%20Gelert%20was%20hesitant%20and%20wary%20-%20after%20all%2C%20strangers%20rarely%20entered%20their%20quiet%20town%20-%20but%20he%20could%20not%20resist%20the%20enticing%20bargain%20and%20took%20the%20potion%20home.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="025" resname="IDS_BOOK1_PAGE2_TEXT8_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThat%20night%2C%20desperate%20to%20see%20his%20troubles%20gone%2C%20Bruno%20drank%20every%20last%20drop%20of%20the%20elixir...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="026" resname="IDS_BOOK1_PAGE2_TEXT9_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThe%20next%20morning%2C%20he%20awoke%20to%20discover%20that%20the%20potion%20had%20indeed%20done%20all%20that%20was%20promised%20of%20it.%20He%20was%20now%20a%20handsome%2C%20strong%2C%20confident%20Gelert%20-%20everything%20he%20had%20wished%20to%20be%2C%20and%20the%20change%20did%20not%20go%20unnoticed.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="027" resname="IDS_BOOK1_PAGE2_TEXT9_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AYou%27re%20looking%20unusually%20well%20today%2C%20son.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="028" resname="IDS_BOOK1_PAGE2_TEXT10_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ABruno%20told%20his%20father%20everything%20about%20the%20potion%20and%20the%20wishes%20it%20had%20granted%2C%20but%20the%20practical%20Edmund%20could%20not%20accept%20such%20good%20fortune%20so%20easily.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="029" resname="IDS_BOOK1_PAGE2_TEXT10_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AProblems%20cannot%20be%20solved%20overnight%20with%20magic%20potions%21%20Success%20is%20only%20achieved%20through%20hard%20work%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="030" resname="IDS_BOOK1_PAGE3_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AUnfortunately%2C%20he%20had%20bigger%20things%20to%20worry%20about%20than%20his%20son%27s%20suddenly%20improved%20physique.%20For%20years%2C%20the%20family%20business%20had%20been%20failing%2C%20and%20their%20struggling%20finances%20had%20been%20a%20constant%20worry%20to%20him.%20Despite%20his%20desire%20to%20keep%20supporting%20his%20family%2C%20business%20only%20seemed%20to%20get%20worse.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="031" resname="IDS_BOOK1_PAGE3_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AConsumed%20with%20worry%2C%20Edmund%20was%20hard%20at%20work%20around%20town%20when%20he%20heard%20a%20voice...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="032" resname="IDS_BOOK1_PAGE3_TEXT2_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AYou%20look%20preoccupied%2C%20dear%20sir.%20Perhaps%20I%20can%20be%20of%20assistance...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="033" resname="IDS_BOOK1_PAGE3_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThis%20elixir%20will%20chase%20away%20all%20sorrows%20and%20fulfill%20all%20desires.%20Whatever%20you%20want%20in%20life%2C%20it%20will%20grant.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="034" resname="IDS_BOOK1_PAGE3_TEXT3_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AEdmund%20immediately%20realised%20that%20this%20potion%20was%20the%20one%20his%20son%20had%20taken%2C%20but%20despite%20his%20previous%20misgivings%2C%20he%20could%20not%20restrain%20a%20rush%20of%20hope%20and%20longing.%20Weighed%20down%20with%20desperate%20anxiety%2C%20he%20decided%20that%20he%20had%20nothing%20to%20lose%20and%20took%20the%20bottle%20home.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="035" resname="IDS_BOOK1_PAGE3_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AOver%20the%20next%20few%20days%2C%20Edmund%20was%20delighted%20to%20discover%20that%20his%20son%20had%20spoken%20the%20truth.%20With%20just%20a%20sip%20of%20the%20potion%2C%20all%20his%20financial%20worries%20vanished%20into%20the%20mist.%20He%20found%20himself%20in%20a%20prospering%20business%20again%2C%20cutting%20good%20deals%20at%20every%20turn%2C%20and%20freed%20of%20the%20debt%20that%20had%20plagued%20him%20for%20years.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="036" resname="IDS_BOOK1_PAGE3_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AWord%20soon%20spread%20about%20the%20wonders%20the%20potion%20had%20done%20for%20the%20family.%20Edmund%20and%20Bruno%20were%20its%20principal%20advocates%2C%20eager%20to%20tell%20their%20story%20to%20anyone%20who%20asked.%20Even%20Reginald%2C%20who%20had%20taken%20it%20to%20achieve%20knowledge%2C%20did%20not%20hesitate%20to%20back%20up%20his%20father%20and%20brother.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="037" resname="IDS_BOOK1_PAGE3_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ASoon%20the%20entire%20town%20was%20clamoring%20for%20these%20magical%20elixirs.%20Every%20father%2C%20mother%2C%20son%2C%20and%20daughter%20lined%20the%20streets%2C%20for%20there%20are%20few%20who%20do%20not%20long%20for%20more%20in%20this%20world.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="038" resname="IDS_BOOK1_PAGE3_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AOnly%20the%20innocent%2C%20those%20with%20not%20a%20care%20in%20the%20world%2C%20did%20not%20wish%20to%20drink%2C%20and%20there%20were%20precious%20few%20of%20them...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="039" resname="IDS_BOOK1_PAGE3_TEXT7_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AReginald%2C%20come%20and%20play%20with%20me%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="040" resname="IDS_BOOK1_PAGE3_TEXT7_BUBBLE3">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%27ll%20be%20there%20in%20a%20moment%2C%20sister.%20Just%20let%20me%20finish%20this%20book...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="041" resname="IDS_BOOK1_PAGE3_TEXT8_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThe%20rest%20of%20the%20townspeople%20drank%20the%20elixirs%20in%20earnest%2C%20greedily%20believing%20that%20all%20their%20wishes%20would%20be%20fulfilled%20overnight.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="042" resname="IDS_BOOK1_PAGE3_TEXT9_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AAnd%20at%20first%2C%20it%20seemed%20like%20those%20dreams%20had%20all%20come%20true...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="043" resname="IDS_BOOK1_PAGE3_TEXT9_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ATo%20be%20continued...%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
  </body>
  <system>
   <langs>
    <lang>
     <name>English</name>
     <code>en</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Nederlands</name>
     <code>nl</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Portugu%C3%AAs</name>
     <code>pt</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Deutsch</name>
     <code>de</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Fran%C3%A7ais</name>
     <code>fr</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Italiano</name>
     <code>it</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Espa%C3%B1ol</name>
     <code>es</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87</name>
     <code>ch</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87</name>
     <code>zh</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E6%97%A5%E6%9C%AC%E8%AA%9E</name>
     <code>ja</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%ED%95%9C%EA%B5%AD%EC%96%B4</name>
     <code>ko</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
   </langs>
  </system>
 </file>
</xliff>
