<!DOCTYPE xliff PUBLIC "-//XLIFF//DTD XLIFF//EN"
 "http://www.oasis-open.org/committees/xliff/documents/xliff.dtd" >
<xliff version="1.0" xml:lang="en">
 <file datatype="plaintext" original="900107" source-language="EN">
  <header></header>
  <body>
<trans-unit id="001" resname="TRANSLATION_TITLE">
<source>Comic%20Pages%3A%20Haunted%20Woods%2C%20Chapter%204</source>
</trans-unit>
<trans-unit id="002" resname="IDS_PREVIOUS_PAGE">
<source>%3Cp%20align%3D%27left%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3EBack%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="003" resname="IDS_NEXT_PAGE">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3ENext%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="004" resname="IDS_BOOK7_PAGE1_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AHello%2C%20Sophie.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="005" resname="IDS_BOOK7_PAGE1_TEXT2_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AIlere.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="006" resname="IDS_BOOK7_PAGE1_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AWe%20need%20your%20help.%20%20Neovia%20is%20under%20some%20sort%20of%20spell.%20%20Every%20year%20on%20Halloween%2C%20ghostly%20versions%20of%20the%20townspeople%20appear%2C%20but%20they%27re%20gone%20by%20the%20next%20morning%20and%20don%27t%20show%20up%20for%20another%20year.%20%20We%20think%20it%27s%20the%20work%20of%20this%20guy--%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="007" resname="IDS_BOOK7_PAGE1_TEXT3_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0A--called%20the%20Spirit%20of%20Slumber%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="008" resname="IDS_BOOK7_PAGE1_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AHe%20was%20summoned%20by%20the%20Mayor%20and%20the%20townspeople%20at%20the%20height%20of%20Neovia%27s%20need.%20%20This%20was%20his%20%22solution%22%20for%20the%20havoc%20the%20potions%20had%20wreaked.%20%20We%20want%20to%20find%20him%20so%20he%20can%20reverse%20the%20spell%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="009" resname="IDS_BOOK7_PAGE1_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AThe%20Spirit%20of%20Slumber%3F%20%20You%27re%20mad.%20%20None%20of%20you%20have%20any%20idea%20what%20you%27re%20dealing%20with%3B%20power%20like%20his%20is%20not%20to%20be%20trifled%20with.%20%20Go%20home%20before%20you%20get%20hurt.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="010" resname="IDS_BOOK7_PAGE1_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AI%27VE%20HEARD%20ENOUGH%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="011" resname="IDS_BOOK7_PAGE1_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0A%2AZAP%21%2A%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="012" resname="IDS_BOOK7_PAGE2_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ARrrrrrrr--%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="013" resname="IDS_BOOK7_PAGE2_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ASTOP%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="014" resname="IDS_BOOK7_PAGE2_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AWhat%20do%20you%20think%20you%27re%20doing%2C%20Bruno%3F%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="015" resname="IDS_BOOK7_PAGE2_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AThis%20earth%20faerie%20is%20powerful%20--%20I%20can%20feel%20it%20--%20and%20yet%20she%20does%20nothing%21%20%20She%20left%20you%20to%20fend%20for%20yourself%20all%20those%20years%20and%20never%20lifted%20a%20finger%20to%20aid%20Neovia%2C%20and%20now%20she%20won%27t%20even%20give%20us%20a%20single%20helping%20word%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="016" resname="IDS_BOOK7_PAGE2_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AYou%20are%20not%20as%20weak%20as%20I%20thought.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="017" resname="IDS_BOOK7_PAGE2_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AIf%20you%20don%27t%20tell%20us%20about%20the%20Spirit%20of%20Slumber%2C%20I%27ll%20show%20you%20just%20how%20strong%20I%20am.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="018" resname="IDS_BOOK7_PAGE2_TEXT8_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AVery%20well.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="019" resname="IDS_BOOK7_PAGE2_TEXT10_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AHe%20used%20to%20be%20a%20Neopet%20in%20life%2C%20but%20he%20became%20a%20powerful%20spirit%20of%20these%20woods%20when%20he%20died.%20%20I%27ve%20never%20seen%20him%20myself%3B%20they%20say%20he%20appears%20and%20vanishes%20as%20mysteriously%20as%20the%20morning%20mist.%20%20There%20are%20many%20denizens%20in%20these%20woods%20that%20have%20lived%20here%20longer%20than%20I%2C%20however.%20%20They%20might%20be%20more%20well-versed%20in%20the%20ancient%20lore%20of%20this%20forest.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="020" resname="IDS_BOOK7_PAGE2_TEXT11_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ASophie...%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="021" resname="IDS_BOOK7_PAGE2_TEXT12_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AFor%20your%20own%20sake%2C%20I%20hope%20you%20fail.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="022" resname="IDS_BOOK7_PAGE2_TEXT12_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ATo%20be%20continued...%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
  </body>
  <system>
   <langs>
    <lang>
     <name>English</name>
     <code>en</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Nederlands</name>
     <code>nl</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Portugu%C3%AAs</name>
     <code>pt</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Deutsch</name>
     <code>de</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Fran%C3%A7ais</name>
     <code>fr</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Italiano</name>
     <code>it</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Espa%C3%B1ol</name>
     <code>es</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87</name>
     <code>ch</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87</name>
     <code>zh</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E6%97%A5%E6%9C%AC%E8%AA%9E</name>
     <code>ja</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%ED%95%9C%EA%B5%AD%EC%96%B4</name>
     <code>ko</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
   </langs>
  </system>
 </file>
</xliff>