<!DOCTYPE xliff PUBLIC "-//XLIFF//DTD XLIFF//EN"
 "http://www.oasis-open.org/committees/xliff/documents/xliff.dtd" >
<xliff version="1.0" xml:lang="en">
 <file datatype="plaintext" original="900108" source-language="EN">
  <header></header>
  <body>
<trans-unit id="001" resname="TRANSLATION_TITLE">
<source>Comic%20Pages%3A%20Haunted%20Woods%2C%20Chapter%205</source>
</trans-unit>
<trans-unit id="002" resname="IDS_PREVIOUS_PAGE">
<source>%3Cp%20align%3D%27left%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3EBack%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="003" resname="IDS_NEXT_PAGE">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3ENext%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="004" resname="IDS_BOOK8_PAGE1_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AStill%20no%20real%20help%20from%20that%20earth%20faerie.%20%20Where%20do%20we%20go%20now%3F%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="005" resname="IDS_BOOK8_PAGE1_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AWell%2C%20Ilere%20told%20us%20to%20look%20for%20denizens%20of%20the%20forest%20who%20have%20lived%20here%20longer%20than%20she%20has.%20%20Maybe%20we%20could%20try%20talking%20to%20the%20Br--%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="006" resname="IDS_BOOK8_PAGE1_TEXT2_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ANO%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="007" resname="IDS_BOOK8_PAGE1_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ABut%20the%20Brain%20Tree%20has%20lived%20here%20for%20so%20long%21%20%20He%20might%20know%20the%20name%20of%20the%20Spirit%20of%20Slumber%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="008" resname="IDS_BOOK8_PAGE1_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AI%20had%20a%20bad%20experience%20with%20the%20Brain%20Tree.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="009" resname="IDS_BOOK8_PAGE1_TEXT4_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AWhat%20happened%3F%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="010" resname="IDS_BOOK8_PAGE1_TEXT4_BUBBLE3">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AI%20HAD%20A%20BAD%20EXPERIENCE%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="011" resname="IDS_BOOK8_PAGE1_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ACome%20on%21%20%20It%20won%27t%20be%20that%20bad%2C%20I%27m%20sure.%20%20We%27ll%20just%20pop%20over%20and%20ask--%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="012" resname="IDS_BOOK8_PAGE1_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AI%20said%20NO%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="013" resname="IDS_BOOK8_PAGE1_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ASophie%21%20%20What%20do%20you%20think%20you%27re%20doing%3F%21%20%20I%20don%27t%20know%20what%20happened%20between%20you%20and%20the%20Brain%20Tree%2C%20but%20you%20know%20he%20probably%20has%20information%20that%20is%20vital%20to%20us%21%20%20Surely%20you%20could%20overcome%20your%20grudge%20long%20enough%20to%20realise%20that.%20%20Gilly%20was%20only%20trying%20to%20help%20us%2C%20and%20she%27s%20just%20a%20little%20girl%21%20%20Blasting%20her%20was%20uncalled%20for.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="014" resname="IDS_BOOK8_PAGE1_TEXT7_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0A...%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="015" resname="IDS_BOOK8_PAGE1_TEXT8_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AAnnoying%20little%20twerp...%20I%20oughta-%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="016" resname="IDS_BOOK8_PAGE1_TEXT8_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ASophie...%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="017" resname="IDS_BOOK8_PAGE1_TEXT8_BUBBLE3">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0A...I%27m%20sorry.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="018" resname="IDS_BOOK8_PAGE2_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AExcuse%20us%2C%20Mr.%20Brain%20Tree%2C%20but%20can%20you%20tell%20us%20who%20the%20Spirit%20of%20Slumber%20is%3F%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="019" resname="IDS_BOOK8_PAGE2_TEXT1_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AThe%20Spirit%20of%20Slumber%3F%20%20Tell%20me%20when%20he%20died%2C%20and%20I%27ll%20tell%20you%20his%20real%20name.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="020" resname="IDS_BOOK8_PAGE2_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AWell%2C%20that%27s%20easy%21%20%20We%27ll%20just%20ask%20the%20Esophagor.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="021" resname="IDS_BOOK8_PAGE2_TEXT2_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AWHAT%3F%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="022" resname="IDS_BOOK8_PAGE2_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ANo%21%20%20I%20had%20a%20bad--%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="023" resname="IDS_BOOK8_PAGE2_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ANever%20mind.%20%20Fine.%20%20Let%27s%20go.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="024" resname="IDS_BOOK8_PAGE2_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AIIII%20caaan%20ooonlyy%20teeeell%20yoooou%20wheeen%20sooomeooone%20diiiiied%20iiiiiif%20theeey%20aaaaactuaaallyyy%20diiiied.%20%20Theeeee%20Spiiiiriiiiiittt%20ooooffff%20Sluuuummmberrrr%20neeeeveeer%20diiiieed.%20%20Teeell%20meee%20hiiiis%20reeeaaal%20naaaame%2C%20aaaand%20IIII%27ll%20teeeeeell%20yoooou%20wheeeeen%20heeee%20diiiied.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="025" resname="IDS_BOOK8_PAGE2_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AThat%27s%20hardly%20fair%21%20%20We%20need%20the%20name%20to%20know%20when%20he%20died%2C%20but%20we%20need%20to%20find%20out%20when%20he%20died%20to%20know%20the%20name%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="026" resname="IDS_BOOK8_PAGE2_TEXT7_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AThere%20is%20a%20possibility...%20%20If%20we%20can%20find%20his%20bones%2C%20I%20know%20a%20potion%20that%20can%20identify%20him%20from%20the%20remains.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="027" resname="IDS_BOOK8_PAGE2_TEXT8_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ABut%20how%20do%20we%20find%20his%20bones%20if%20we%20don%27t%20know%20where%20he%27s%20buried%3F%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="028" resname="IDS_BOOK8_PAGE2_TEXT8_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AWell%2C%20that%27s%20easy...%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="029" resname="IDS_BOOK8_PAGE2_TEXT9_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AWe%27ll%20just%20dig%20up%20every%20single%20grave%20in%20the%20Haunted%20Woods%20until%20we%20find%20him.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="030" resname="IDS_BOOK8_PAGE2_TEXT10_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0A%2AGulp%2A%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
  </body>
  <system>
   <langs>
    <lang>
     <name>English</name>
     <code>en</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Nederlands</name>
     <code>nl</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Portugu%C3%AAs</name>
     <code>pt</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Deutsch</name>
     <code>de</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Fran%C3%A7ais</name>
     <code>fr</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Italiano</name>
     <code>it</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Espa%C3%B1ol</name>
     <code>es</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87</name>
     <code>ch</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87</name>
     <code>zh</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E6%97%A5%E6%9C%AC%E8%AA%9E</name>
     <code>ja</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%ED%95%9C%EA%B5%AD%EC%96%B4</name>
     <code>ko</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
   </langs>
  </system>
 </file>
</xliff>