<!DOCTYPE xliff PUBLIC "-//XLIFF//DTD XLIFF//EN"
 "http://www.oasis-open.org/committees/xliff/documents/xliff.dtd" >
<xliff version="1.0" xml:lang="en">
 <file datatype="plaintext" original="900106" source-language="EN">
  <header></header>
  <body>
<trans-unit id="001" resname="TRANSLATION_TITLE">
<source>Comic%20Pages%3A%20Haunted%20Woods%2C%20Chapter%203</source>
</trans-unit>
<trans-unit id="002" resname="IDS_PREVIOUS_PAGE">
<source>%3Cp%20align%3D%27left%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3EBack%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="003" resname="IDS_NEXT_PAGE">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3ENext%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="004" resname="IDS_BOOK6_PAGE1_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ASophie%3F%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="005" resname="IDS_BOOK6_PAGE1_TEXT1_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ABrother...%20How%20did%20you...%20What%20happened%20to%20you%20that%20night%3F%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="006" resname="IDS_BOOK6_PAGE1_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%20tried%20to%20calm%20the%20townspeople%20while%20you%20and%20Reginald%20escaped%2C%20but%20they%20turned%20on%20me%20and%20chased%20me%20out%20of%20Neovia.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="007" resname="IDS_BOOK6_PAGE1_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%20made%20a%20headlong%20dash%20into%20the%20woods%2C%20blindly%20crashing%20through%20the%20leaves%20and%20branches%2C%20hotly%20pursued%20by%20the%20Neopets%20who%20had%20once%20been%20my%20friends%20and%20neighbours.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="008" resname="IDS_BOOK6_PAGE1_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%20managed%20to%20lose%20them%20under%20the%20cover%20of%20night%20and%20slipped%20into%20the%20darker%20recesses%20of%20the%20woods%20as%20they%20continued%20to%20search%20for%20me.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="009" resname="IDS_BOOK6_PAGE1_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AEventually%2C%20I%20found%20shelter%20in%20an%20empty%20cave%2C%20and%20I%20remained%20there%20until%20the%20townspeople%20gave%20up.%20%20I%20didn%27t%20dare%20return%20to%20town%2C%20however%2C%20because%20I%20was%20afraid%20that%20I%20would%20merely%20provoke%20them%20again.%20%20I%20stayed%20in%20that%20cave%20and%20made%20it%20my%20home%2C%20and...%20I%20haven%27t%20seen%20my%20family%20since.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="010" resname="IDS_BOOK6_PAGE1_TEXT5_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AWhat%20about%20you%2C%20Sophie%3F%20%20Where%20did%20you%20go%3F%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="011" resname="IDS_BOOK6_PAGE1_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AWe%20ran%20into%20the%20earth%20faerie%20Ilere%2C%20who%20took%20me%20to%20this%20dingy%20old%20shack.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="012" resname="IDS_BOOK6_PAGE1_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AInside%2C%20she%20handed%20me%20a%20magical%20chest%20that%20she%20said%20would%20contain%20everything%20I%20needed%20to%20survive%2C%20and%20then%20she%20vanished.%20%20Some%20protector%2C%20huh%3F%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="013" resname="IDS_BOOK6_PAGE1_TEXT8_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%20returned%20to%20Neovia%20a%20few%20days%20later%20to%20see%20if%20I%20could%20find%20you%20and%20the%20rest%20of%20our%20family%2C%20but%20the%20whole%20place%20was%20deserted.%20%20I%20came%20back%20several%20more%20times%20over%20the%20following%20weeks%2C%20but%20it%20was%20the%20same%20thing%20every%20time.%20%20Everyone%20had%20just%20up%20and%20gone%20-%20to%20where%2C%20I%20had%20no%20idea.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="014" resname="IDS_BOOK6_PAGE1_TEXT9_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AOn%20Halloween%20night%2C%20I%20decided%20to%20return%20one%20last%20time...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="015" resname="IDS_BOOK6_PAGE1_TEXT10_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AYou%20can%20imagine%20my%20surprise%20when%20I%20saw%20the%20town%20bustling%20with%20Neopets%20once%20more.%20%20There%20was%20something%20weird%20about%20them%2C%20though.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="016" resname="IDS_BOOK6_PAGE2_TEXT1_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThey%20went%20about%20their%20daily%20errands%2C%20but%20with%20none%20of%20their%20usual%20bickering%20and%20chatting.%20%20Their%20faces%20were%20entirely%20blank%2C%20and%20their%20bodies%20looked%20like%20they%20were%20only%20going%20through%20the%20motions.%20%20When%20I%20accidentally%20touched%20one%20of%20them%2C%20I%20realised%20that%20these%20weren%27t%20even%20their%20real%20physical%20bodies.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="017" resname="IDS_BOOK6_PAGE2_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%20stayed%20awake%20that%20entire%20night%2C%20poring%20over%20books%20and%20mixing%20potions%20in%20an%20attempt%20to%20find%20a%20cure...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="018" resname="IDS_BOOK6_PAGE2_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0A...but%20when%20I%20revisited%20the%20town%20the%20next%20morning%2C%20it%20was%20once%20again%20empty.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="019" resname="IDS_BOOK6_PAGE2_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ASince%20then%2C%20I%27ve%20spent%20all%20my%20time%20unsuccessfully%20working%20on%20a%20cure.%20%20I%20go%20back%20every%20Halloween%2C%20which%20is%20when%20the%20townspeople%20reappear%2C%20but%20it%20always%20fails.%20%20Had%20I%20known%20you%20had%20escaped%2C%20Bruno%2C%20I%20would%27ve%20looked%20for%20you%20as%20well.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="020" resname="IDS_BOOK6_PAGE2_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThat%20must%20be%20what%20the%20Spirit%20of%20Slumber%20did%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="021" resname="IDS_BOOK6_PAGE2_TEXT5_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThe%20Spirit%20of%20Slumber%3F%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="022" resname="IDS_BOOK6_PAGE2_TEXT5_BUBBLE3">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AYes%2C%20he%20cast%20a%20spell%20on%20the%20town.%20%20There%20must%20be%20a%20way%20to%20reverse%20it%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="023" resname="IDS_BOOK6_PAGE2_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AI%27ve%20been%20working%20on%20this%20for%20ten%20years%2C%20kid.%20%20There%27s%20not%20much%20I%20haven%27t%20tried.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="024" resname="IDS_BOOK6_PAGE2_TEXT6_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ABut%20you%20didn%27t%20know%20about%20the%20Spirit%20of%20Slumber.%20%20I%20think%20we%20can%20still%20figure%20this%20out%20and%20save%20the%20town%20-%20and%20your%20family%2C%20Sophie%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="025" resname="IDS_BOOK6_PAGE2_TEXT6_BUBBLE3">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AWell...%20there%20is%20Ilere.%20%20She%20might%20know%20more%20about%20this%20guy.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="026" resname="IDS_BOOK6_PAGE2_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AIt%20can%27t%20hurt%20to%20look%20for%20the%20earth%20faerie.%20%20With%20any%20luck%2C%20we%27ll%20find%20her%20in%20the%20forest%20near%20here.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="027" resname="IDS_BOOK6_PAGE2_TEXT8_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AHey%2C%20wait%20up%21%20%20I%20want%20to%20help.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="028" resname="IDS_BOOK6_PAGE2_TEXT8_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0ANo%20way%2C%20the%20brat%20isn%27t%20going.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="029" resname="IDS_BOOK6_PAGE2_TEXT9_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AThe%20young%20lady%20isn%27t%20so%20bad.%20%20Let%20her%20go.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="030" resname="IDS_BOOK6_PAGE2_TEXT9_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AFine.%20%20But%20she%27d%20better%20not-%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="031" resname="IDS_BOOK6_PAGE2_TEXT9_BUBBLE3">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%0AGet%20in%20the%20way%3F%20%20Got%20it.%3C%2Ffont%3E</source>
</trans-unit>
  </body>
  <system>
   <langs>
    <lang>
     <name>English</name>
     <code>en</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Nederlands</name>
     <code>nl</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Portugu%C3%AAs</name>
     <code>pt</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Deutsch</name>
     <code>de</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Fran%C3%A7ais</name>
     <code>fr</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Italiano</name>
     <code>it</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Espa%C3%B1ol</name>
     <code>es</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87</name>
     <code>ch</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87</name>
     <code>zh</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E6%97%A5%E6%9C%AC%E8%AA%9E</name>
     <code>ja</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%ED%95%9C%EA%B5%AD%EC%96%B4</name>
     <code>ko</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
   </langs>
  </system>
 </file>
</xliff>