<!DOCTYPE xliff PUBLIC "-//XLIFF//DTD XLIFF//EN"
 "http://www.oasis-open.org/committees/xliff/documents/xliff.dtd" >
<xliff version="1.0" xml:lang="en">
 <file datatype="plaintext" original="900117" source-language="EN">
  <header></header>
  <body>
<trans-unit id="001" resname="TRANSLATION_TITLE">
<source>Comic%20Pages%3A%20Haunted%20Woods%2C%20Chapter%2014</source>
</trans-unit>
<trans-unit id="002" resname="IDS_PREVIOUS_PAGE">
<source>%3Cp%20align%3D%27left%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3EBack%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="003" resname="IDS_NEXT_PAGE">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3ENext%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="004" resname="IDS_BOOK17_PAGE1_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AAmazing...%20it%27s%20still%20fresh.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="005" resname="IDS_BOOK17_PAGE1_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AOof%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="006" resname="IDS_BOOK17_PAGE1_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ASophie%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="007" resname="IDS_BOOK17_PAGE1_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AAre%20you%20all%20right%3F%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="008" resname="IDS_BOOK17_PAGE1_TEXT6_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AI%27m%20fine.%20%20Look%2C%20I%27m%20sorry%20about...%20what%20happened.%20%20But%20you%27re%20right%3B%20we%20need%20to%20kick%20this%20curse%20once%20and%20for--%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="009" resname="IDS_BOOK17_PAGE1_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AWhat%27s%20that%20you%27re%20holding%2C%20kid%3F%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="010" resname="IDS_BOOK17_PAGE1_TEXT8_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AOh%2C%20this%3F%20%20Well%2C%20I%20found%20Krawley%20in%20town%20and%20followed%20him%20to%20this%20old%2C%20abandoned%20asylum.%20%20The%20inhabitants%20were%2C%20um%2C%20long%20gone%2C%20but%20I%20found%20this%20flower%20there%2C%20still%20fresh%20and%20blooming.%20%20Pretty%2C%20isn%27t%20it%3F%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="011" resname="IDS_BOOK17_PAGE1_TEXT8_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AThat%27s%20it%21%20%20That%27s%20the%20ingredient%20I%27m%20missing%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="012" resname="IDS_BOOK17_PAGE1_TEXT10_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AThis%20should%20work%3B%20we%20just%20need%20to%20pour%20it%20into%20the%20town%27s%20well%20now.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="013" resname="IDS_BOOK17_PAGE2_TEXT2_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0A%2AZAP%21%2A%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="014" resname="IDS_BOOK17_PAGE2_TEXT3_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AZAZZAT%21%2A%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="015" resname="IDS_BOOK17_PAGE2_TEXT4_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0A%2APZZZZT%21%2A%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="016" resname="IDS_BOOK17_PAGE2_TEXT5_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AAre%20you%20sure%20about%20this%2C%20Sophie%3F%20%20This%20is%20your%20chance%20--%20just%20go%20home%2C%20and%20forget%20about%20all%20of%20this.%20%20Pretend%20it%20never%20happened.%20%20Why%20invite%20more%20heartache%3F%20%20Honestly%2C%20could%20you%20bear%20it%20if%20it%20didn%27t%20work%3F%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="017" resname="IDS_BOOK17_PAGE2_TEXT6_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AI%27ll%20take%20my%20chances.%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="018" resname="IDS_BOOK17_PAGE2_TEXT7_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ASHOOM%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="019" resname="IDS_BOOK17_PAGE2_TEXT8_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ACRACK%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="020" resname="IDS_BOOK17_PAGE2_TEXT8_BUBBLE2">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AOof%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="021" resname="IDS_BOOK17_PAGE2_TEXT9_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0ARAAAARR%21%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="022" resname="IDS_BOOK17_PAGE2_TEXT10_BUBBLE1">
<source>%3Cfont%20face%20%3D%20%27customComic0_fnt%27%20size%20%3D%20%2718%27%3E%3Cp%20align%3D%27center%27%3E%0AAre%20you%20all%20right%3F%20The%20Mayor%20is%20stronger%20than%20he%20appears...%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
  </body>
  <system>
   <langs>
    <lang>
     <name>English</name>
     <code>en</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Nederlands</name>
     <code>nl</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Portugu%C3%AAs</name>
     <code>pt</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Deutsch</name>
     <code>de</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Fran%C3%A7ais</name>
     <code>fr</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Italiano</name>
     <code>it</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Espa%C3%B1ol</name>
     <code>es</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87</name>
     <code>ch</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87</name>
     <code>zh</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E6%97%A5%E6%9C%AC%E8%AA%9E</name>
     <code>ja</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%ED%95%9C%EA%B5%AD%EC%96%B4</name>
     <code>ko</code>
     <enabled>1</enabled>
     <langgroup>NW</langgroup>
    </lang>
   </langs>
  </system>
 </file>
</xliff>