<?php 
switch ($_POST["handling"])
{
	case "load":
		echo "k=3914388";
		break;
	case "spill":
		echo "status=spillet_er_registrert";
		break;
	case "lagrespill":
		echo "plassering=&dagens_nr_fem=";
		break;
	case "highscorelister":
		echo '<?xml version="1.0"?><highscorelister><norge>
<oppforing>
<plassering>1</plassering>
<nick><![CDATA[Raboman]]></nick>
<poeng>27</poeng>
<land>no</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>2</plassering>
<nick><![CDATA[Raboman]]></nick>
<poeng>11</poeng>
<land>no</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>3</plassering>
<nick><![CDATA[Raboman]]></nick>
<poeng>3</poeng>
<land>no</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>4</plassering>
<nick><![CDATA[master]]></nick>
<poeng>1</poeng>
<land>no</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>5</plassering>
<nick><![CDATA[master]]></nick>
<poeng>1</poeng>
<land>no</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>6</plassering>
<nick><![CDATA[Haraldv8]]></nick>
<poeng>3</poeng>
<land>no</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>7</plassering>
<nick><![CDATA[Haraldv8]]></nick>
<poeng>1</poeng>
<land>no</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>8</plassering>
<nick><![CDATA[ghyuhifd]]></nick>
<poeng>5</poeng>
<land>no</land>
<streng><![CDATA[]]></streng>
</oppforing>
</norge>
<sverige>
<oppforing>
<plassering>1</plassering>
<nick><![CDATA[Anton]]></nick>
<poeng>1</poeng>
<land>se</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>2</plassering>
<nick><![CDATA[Anton]]></nick>
<poeng>0</poeng>
<land>se</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>3</plassering>
<nick><![CDATA[Anton]]></nick>
<poeng>2</poeng>
<land>se</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>4</plassering>
<nick><![CDATA[Anton]]></nick>
<poeng>1</poeng>
<land>se</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>5</plassering>
<nick><![CDATA[Anton]]></nick>
<poeng>0</poeng>
<land>se</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>6</plassering>
<nick><![CDATA[Stordelfi]]></nick>
<poeng>4</poeng>
<land>se</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>7</plassering>
<nick><![CDATA[Unknown Duck]]></nick>
<poeng>0</poeng>
<land>se</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>8</plassering>
<nick><![CDATA[Unknown Duck]]></nick>
<poeng>1</poeng>
<land>se</land>
<streng><![CDATA[]]></streng>
</oppforing>
</sverige>
<danmark>
<oppforing>
<plassering>1</plassering>
<nick><![CDATA[andeby fc]]></nick>
<poeng>3</poeng>
<land>dk</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>2</plassering>
<nick><![CDATA[andeby fc]]></nick>
<poeng>0</poeng>
<land>dk</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>3</plassering>
<nick><![CDATA[master]]></nick>
<poeng>3</poeng>
<land>dk</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>4</plassering>
<nick><![CDATA[master]]></nick>
<poeng>1</poeng>
<land>dk</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>5</plassering>
<nick><![CDATA[Anonym]]></nick>
<poeng>0</poeng>
<land>dk</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>6</plassering>
<nick><![CDATA[Anonym]]></nick>
<poeng>2</poeng>
<land>dk</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>7</plassering>
<nick><![CDATA[Anonym]]></nick>
<poeng>3</poeng>
<land>dk</land>
<streng><![CDATA[]]></streng>
</oppforing>
<oppforing>
<plassering>8</plassering>
<nick><![CDATA[emilfifa]]></nick>
<poeng>5</poeng>
<land>dk</land>
<streng><![CDATA[]]></streng>
</oppforing>
</danmark>
<tot_no>1935217</tot_no>
<tot_se>2969193</tot_se>
<tot_dk>4398115</tot_dk>
</highscorelister>';
		break;
}
?>